name: Fork Sync

on:
  schedule:
  - cron: '0 12 * * 0'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: TG908/fork-sync@v1.1.7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: evennia
        base: master
        head: master
